name: data_provider
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4

dev_dependencies:
  freezed: ^3.2.5
  json_serializable: ^6.12.0
  build_runner: ^2.11.0
  injectable_generator: ^2.12.0
  lints: ^6.0.0
  test: ^1.25.6
